### ISSUE TITLE
Creating a plugin from this

### ISSUE THREAD

**Issue by Bluscream** [landave/TeamSpeakHasher#10]
@alex720 and i want to create a Teamspeak plugin based on TeamspeakHashers functions, if that's okay i'd like to keep some of the thoughts here so you can give your opinion if you want ❤️

**Comment by Bluscream** [comment]
So the plugin base should be easy since Teamspeak's plugin API is C++ compatible

- [ ] Read and parse Identities from `%appdata%\TS3Client\settings.db` in the `ProtobufItems` table.
- [ ] Build Qt UI with a listwidget to switch between Identities and a section for info's/actions

**Comment by landave** [comment]
Note that extracting the public key from the database string is exactly what [TSIdentityTool](https://github.com/landave/TSIdentityTool) implements. So you probably want to integrate this as well into the plugin.

Moreover, I recommend **not** to display the private key in the GUI, since this will definitely cause users to leak their private key. Obviously, the same applies to the obfuscated identity string as well. If you really want to display this, please add a warning to the GUI.

Finally, I would strongly prefer the term "counter" as opposed to "offset", since the latter is misleading.

**Comment by Bluscream** [comment]
1) Right, it can "decode" the final identity string containing the "counter" and the private key but we'll need to read all the identity strings from that giant blob of protobuf either byte by byte or using a protobuf "de-obfuscator" first. That's going to be the tricky part. (putting it back in with the new counter wil, be even more tricky but that's low prio.)

2) users of the plugin are not supposed to screenshot this but yeah i can add a warning messagebox that shows up on first use

3) i'll try but i cant promise anything cause it was always refered to as offset for me since i started learning about teamspeak IDs from @Splamy

**Comment by Splamy** [comment]
Heh, it might be misleading but teamspeak itself calls it `client_key_offset`

**Comment by landave** [comment]
That is hardly an argument. Teamspeak doesn't expose this name publicly, so there is no reason to stick to their bad internal naming.
